name: tgr-microseismic
channels:
  - conda-forge
dependencies:
  - python=3.11
  - graphviz
  - gmt=6.5
  - numpy
  - pandas
  - matplotlib
  - obspy
  - jupyterlab
  - nbclient
  - pytest
  - pip
  - pip:
      - -e .[analysis,test,inference]

